### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by victoruni** [eschnou/ardrone-autonomy#1]
Hello!

How to install? - detailed description can be installed and run a simple example?

**Comment by eschnou** [comment]
It is a standard nodejs project, you can simply git clone the repo and then run 'npm install'. You can find some basic example in the readme. I'll package a npm module in the coming days.

**Comment by eschnou** [comment]
The package is now available on npm, thus can be installed with `npm install ardrone-autonomy`
