### ISSUE TITLE
How do I make the drone move in two directions at the same time?

### ISSUE THREAD

**Issue by nakul-talwar** [eschnou/ardrone-autonomy#16]
Say I want the drone to move to a point given by a specific vector with an x component and a y component. How would I make the drone move along the direction of the vector and not in 2 steps (eg. first 10 m forward then 5 m to the right)? How can I run two commands at the same time?

**Comment by eschnou** [comment]
You have to use the go command and specify the coordinates of the destination, such as  such as {x: 0, y: 0, z: 1, yaw: 90}.

https://github.com/eschnou/ardrone-autonomy#missiongoposition
