### ISSUE TITLE
Exception when trying to run the sample program

### ISSUE THREAD

**Issue by joshuafr** [eschnou/ardrone-autonomy#6]
I'm a drone and JavaScript newbie trying to mess around with this API. I've installed this library using `npm install ardrone-autonomy` and copy/pasted the code in the Mission section of the README. When I connect to my drone and try to run said code, I get the following exception:

```
$node autonomy-test.js

/Users/jfranklin/node_modules/ardrone-autonomy/lib/EKF.js:37
    var pitch = data.demo.rotation.pitch.toRad()
                         ^
TypeError: Cannot read property 'rotation' of undefined
    at EKF.predict (/Users/jfranklin/node_modules/ardrone-autonomy/lib/EKF.js:37:26)
    at Controller._processNavdata (/Users/jfranklin/node_modules/ardrone-autonomy/lib/Controller.js:259:15)
    at Client.<anonymous> (/Users/jfranklin/node_modules/ardrone-autonomy/lib/Controller.js:60:18)
    at Client.EventEmitter.emit (events.js:95:17)
    at Client._handleNavdata (/Users/jfranklin/node_modules/ar-drone/lib/Client.js:120:8)
    at UdpNavdataStream.EventEmitter.emit (events.js:95:17)
    at UdpNavdataStream._handleMessage (/Users/jfranklin/node_modules/ar-drone/lib/navdata/UdpNavdataStream.js:73:10)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:437:8)
```

Am I doing something wrong? If so, what?

**Comment by eschnou** [comment]
Well, I may have forgotten something in the example from the README, not sure about that. Best would be to test by running one of the script in the examples folder. You could try the hover.js script which simply makes the drone climb to 1.5m and hover there for 30 seconds.

Let me know if that works!

**Comment by eschnou** [comment]
If you run hover.js, it should behave like on this video: https://www.youtube.com/watch?v=PA0voAWISYo

**Comment by joshuafr** [comment]
Thanks for the reply. I posted that from one of the sessions at Codemash, so I don't have access to the drones at this point to try that. Sorry I can't try that again to give more information.

For what it's worth, the code I was running was based on hover.js; I had added a movement to go to (1,0,2.5) and a third to go to (0,0,3.5). I also altered the autonomy require (to `autonomy = require('ardrone-autonomy')`) since I was trying to run it in a different directory. Perhaps this was the wrong thing to do? Full code attached:

```
var df = require('dateformat')
  , autonomy = require('ardrone-autonomy')
  , mission  = autonomy.createMission()
  , arDrone = require('ar-drone')
  , arDroneConstants = require('ar-drone/lib/constants')
  ;

function navdata_option_mask(c) {
  return 1 << c;
}

// From the SDK.
var navdata_options = (
    navdata_option_mask(arDroneConstants.options.DEMO)
  | navdata_option_mask(arDroneConstants.options.VISION_DETECT)
  | navdata_option_mask(arDroneConstants.options.MAGNETO)
  | navdata_option_mask(arDroneConstants.options.WIFI)
);

// Connect and configure the drone
mission.client().config('general:navdata_demo', true);
mission.client().config('general:navdata_options', navdata_options);
mission.client().config('video:video_channel', 1);
mission.client().config('detect:detect_type', 12);

mission.log("mission-" + df(new Date(), "yyyy-mm-dd_hh-MM-ss") + ".txt");

mission.takeoff()
       .go({x:0, y:0, z:1.5})
       .hover(3000)
       .go({x:1, y:0, z:2.5})
       .hover(3000)
       .go({x:0, y:0, z:3.5})
       .land();

mission.run(function (err, result) {
    if (err) {
        console.trace("Oops, something bad happened: %s", err.message);
        mission.client().stop();
        mission.client().land();
    } else {
        console.log("We are done!");
        process.exit(0);
    }
});

```

And from the node shell:

```
$ node
> require('ardrone-autonomy')
{ EKF: { [Function: EKF] DELTA_T: 0.06666666666666667 },
  Camera: [Function: Camera],
  Controller:
   { [Function: Controller]
     super_: { [Function: EventEmitter] listenerCount: [Function] } },
  Mission: [Function: Mission],
  control: [Function],
  createMission: [Function] }
```

I hope that clarifies things. Sorry I can't actually try running the drone again. Let me know if there's anything else I might be able to do without the drone to clarify.

**Comment by eschnou** [comment]
No worries and thanks for reporting this, without more details I would guess it is a race condition similar to issue #3 and I just need to push the fix. Thx!
