### ISSUE TITLE
hovering_range tum_simulation/after takeoff

### ISSUE THREAD

**Issue by zweistein** [eschnou/ardrone-autonomy#7]
I'm using the tum_simulator and i dont know where or how to set the hovering_range, like in the launch file.

Is there any commanads after takoff which sets the hovering_range?

**Comment by eschnou** [comment]
I think you may have mistaken this repo with this one: https://github.com/tum-vision/ardrone_autonomy

Both have indeed the same name and achieve the same goal, but this one is written in nodejs, while the other one is written for ROS.

**Comment by zweistein** [comment]
sorry, my mistake
